from django.urls import path
from . import views

urlpatterns = [
    path('',                 views.login_view,          name='login'),
    path('login-submit/',    views.login_view,          name='login_submit'),
    path('signup/',          views.signup_view,         name='signup'),
    path('logout/',          views.logout_view,         name='logout'),
    path('home/',           views.home_view,            name='home'),
    path('inbox/',          views.inbox_view,           name='inbox'),
    path('reels/',          views.reels_view,           name='reels'),
    path('support/',        views.support_view,         name='support'),
    path('profile/',        views.profile_view,         name='profile'),
    path('forgot-password/', views.forgot_password_view, name='forgot_password'),
    path('api/mood-chips/',    views.get_mood_chips,    name='mood_chips'),
    path('api/checkin/',       views.submit_checkin,    name='submit_checkin'),
    path('api/mood-history/',  views.get_mood_history,  name='mood_history'),
    path('api/literacy/',      views.get_literacy,      name='literacy'),
    path('api/chat/',           views.continue_chat,    name='continue_chat'),
    path('api/chat-history/', views.get_chat_history,   name='chat_history'),
    path('api/search-users/', views.search_users,      name='search_users'),
    path('api/conversations/', views.get_conversations, name='get_conversations'),
    path('api/conversations/<int:conversation_id>/messages/',         views.get_messages,      name='get_messages'),
    path('api/send-message/',   views.send_message,      name='send_message'),
    path('api/user-profile/<int:user_id>/', views.get_user_profile,  name='user_profile'),
    path('api/inbox-chat/', views.inbox_chomi_chat,  name='inbox_chat'),
    path('api/toggle-anonymous/', views.toggle_anonymous, name='toggle_anonymous'),
    path('api/update-profile/', views.update_profile, name='update_profile'),
    path('api/clear-data/',     views.clear_data,     name='clear_data'),
    path('api/emergency-contacts/',              views.get_emergency_contacts,    name='get_emergency_contacts'),
    path('api/emergency-contacts/add/',          views.add_emergency_contact,     name='add_emergency_contact'),
    path('api/emergency-contacts/<int:contact_id>/delete/', views.delete_emergency_contact, name='delete_emergency_contact'),
    path('dashboard/', views.dashboard_view, name='dashboard'),
    path('dashboard/admin/',     views.admin_portal_view,        name='admin_portal'),
    path('dashboard/research/',  views.research_dashboard_view,  name='research_dashboard'),
    path('api/admin/stats/',                  views.admin_stats,       name='admin_stats'),
    path('api/admin/users/',                  views.admin_users,       name='admin_users'),
    path('api/admin/users/<int:user_id>/verify/', views.admin_verify_user, name='admin_verify_user'),
]